CREATE TABLE [dbo].[CheckOutcome] (
    Id UNIQUEIDENTIFIER PRIMARY KEY,        
    [MCNotFound] bit NULL,
    [MCNotMatch] bit NULL,
    [MCNotMatchActual] NVARCHAR(15) NULL,
    [VCNotMatchPTD] bit NULL,
    [OIFailPotentialCommercial] bit NULL,
    [OIFailAuthTravellerNoConfirmation] bit NULL,
    [OIFailOther] bit NULL,
    [PassengerTypeId] int NULL,
    [RelevantComments] NVARCHAR(500) NULL, 
    [GBRefersToDAERAOrSPS] BIT NULL, 
    [GBAdviseNoTravel] BIT NULL, 
    [GBPassengerSaysNoTravel] BIT NULL, 
    [SPSOutcome] BIT NULL,
    [SPSOutcomeDetails] NVARCHAR(500) NULL,
    [CreatedBy] UNIQUEIDENTIFIER NULL,
	[CreatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[UpdatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
    [Superseded] BIT NULL, 
    FOREIGN KEY ([PassengerTypeId]) REFERENCES [dbo].[PasengerType]([Id]),
);