CREATE TABLE [dbo].[CheckSummary] (
    Id uniqueidentifier PRIMARY KEY,
    GBCheck bit NULL,
    LinkedCheckId uniqueidentifier,
    CheckerId uniqueidentifier,
    [FlightNo] NVARCHAR(8) NULL, 
    RouteId int,
    [Date] date,
    ScheduledSailingTime time,
    ApplicationId uniqueidentifier,
    TravelDocumentId uniqueidentifier,
    ChipNumber nvarchar(15) ,    
    CheckOutcome bit NULL,
    CheckOutcomeId uniqueidentifier,
    [CreatedBy] UNIQUEIDENTIFIER NULL,
	[CreatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[UpdatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
    [Superseded] BIT NULL DEFAULT 0, 
    FOREIGN KEY (CheckOutcomeId) REFERENCES [dbo].[CheckOutcome]([Id]),    
    FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[Application]([Id]),
    FOREIGN KEY ([TravelDocumentId]) REFERENCES [dbo].[TravelDocument]([Id]),
    FOREIGN KEY ([RouteId]) REFERENCES [dbo].[Route]([Id]),
    FOREIGN KEY (CheckerId) REFERENCES [dbo].[Checker]([Id]),
    FOREIGN KEY (LinkedCheckId) REFERENCES [dbo].[CheckSummary]([Id]),    
);
