CREATE TABLE [dbo].[Owner]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[FullName] NVARCHAR(300) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Telephone]  NVARCHAR(50) NULL,
	[OwnerType] NVARCHAR(20) NULL,
	[CharityName] NVARCHAR(100) NULL,
	[AddressId] UNIQUEIDENTIFIER NULL,
	[CreatedBy] UNIQUEIDENTIFIER NULL,
	[CreatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[UpdatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE()
	CONSTRAINT [FK_Owner_Address] FOREIGN KEY([AddressId]) REFERENCES [dbo].[Address] ([Id])
)
