CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[FullName] NVARCHAR(300) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[FirstName] NVARCHAR(100) NOT NULL,
	[Lastname] NVARCHAR(100) NOT NULL,
	[AddressId] UNIQUEIDENTIFIER NULL,
	[Role] NVARCHAR(100) NOT NULL,
	[Telephone]  NVARCHAR(50) NULL,
	[ContactId] UNIQUEIDENTIFIER NULL,
	[UniqueReference] NVARCHAR(100) NULL,
	[SignInDateTime] DATETIME2(7) NULL,
	[SignOutDateTime] DATETIME2(7) NULL,
	[CreatedBy] UNIQUEIDENTIFIER NULL,
	[CreatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[UpdatedOn] DATETIME2(7) NULL DEFAULT GETUTCDATE()
	CONSTRAINT UK_UserEmail UNIQUE([Email]),
	CONSTRAINT [FK_User_Address] FOREIGN KEY([AddressId]) REFERENCES [dbo].[Address] ([Id])
)
